let li34ri1 = [
  "Mönchhofstraße",
  "Schmidtstraße",
  "Römerhof",
  "Messeparkhaus",
  "Zum Rebstockbad",
  "Rebstockbad",
  "Leonardo-Da-Vinci-Allee",
  "Postsiedlung",
  "Sternbrücke",
  "Parkweg",
  "Alt-Rödelheim",
  "Lorscher Straße",
  "Rödelheim Bahnhof",
  "Radilostraße",
  "Reifenberger Straße/Sozialzentrum",
  "Hausener Weg",
  "Fischstein",
  "Industriehof",
  "Schönhof",
  "Kirchplatz",
  "Sophienstraße",
  "Universitätssportanlagen",
  "Markus-Krankenhaus",
  "Europaturm",
  "Deutsche Bundesbank",
  "Platenstraße",
  "Dornbusch",
  "Kaiser-Sigmund-Straße",
  "Marbachweg/Sozialzentrum",
  "Homburger Landstraße/Marbachweg",
  "Wetzlarer Straße",
  "Friedberger Warte",
  "Friedhof Bornheim",
  "Comeniusstraße",
  "Usinger Straße",
  "Prüfling",
  "Bornheim Mitte"
];

var li34ri2 = [
  "Bornheim Mitte",
  "Prüfling",
  "Usinger Straße",
  "Comeniusstraße",
  "Friedhof Bornheim",
  "Friedberger Warte",
  "Wetzlarer Straße",
  "Homburger Landstraße/Marbachweg",
  "Marbachweg/Sozialzentrum",
  "Kaiser-Sigmund-Straße",
  "Dornbusch",
  "Platenstraße",
  "Deutsche Bundesbank",
  "Europaturm",
  "Markus-Krankenhaus",
  "Universitätssportanlagen",
  "Sophienstraße",
  "Kirchplatz",
  "Schönhof",
  "Industriehof",
  "Fischstein",
  "Hausener Weg",
  "Reifenberger Straße/Sozialzentrum",
  "Lorscher Straße",
  "Rödelheim Bahnhof",
  "Radilostraße",
  "Alt-Rödelheim",
  "Parkweg",
  "Sternbrücke",
  "Postsiedlung",
  "Leonardo-Da-Vinci-Allee",
  "Rebstockbad",
  "Zum Rebstockbad",
  "Messeparkhaus",
  "Römerhof",
  "Schmidtstraße",
  "Mönchhofstraße",
];


export function getBusline(number, direction) {
  if (number === 34 && direction === 1) {return li34ri1;}
  if (number === 34 && direction === 2) {return li34ri2;}
  return [];
};
